# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "psldm-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "The shared user interface of the PSLDM greeter and locker"

[dependencies]
gtk.workspace = true
gtk4-layer-shell.workspace = true
gtk4-session-lock.workspace = true
psldm-auth.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
gtk.workspace = true
